DATASET:
  DATA_PATH: /home/catkin_ws/src/habitat_ros_interface/data/datasets/pointnav/mp3d/v1/test/content/1LXtFkjw3qL0.json.gz
  SCENES_DIR: /home/catkin_ws/src/habitat_ros_interface/data/scene_datasets
  SPLIT: test
  TYPE: PointNav-v1
ENVIRONMENT:
  MAX_EPISODE_STEPS: 500
SIMULATOR:
  AGENT_0:
    SENSORS:
    - RGB_SENSOR
  DEPTH_SENSOR:
    HEIGHT: 256
    WIDTH: 256
  HABITAT_SIM_V0:
    GPU_DEVICE_ID: 0
  RGB_SENSOR:
    HEIGHT: 256
    WIDTH: 256
TASK:
  GOAL_SENSOR_UUID: pointgoal_with_gps_compass
  MEASUREMENTS:
  - DISTANCE_TO_GOAL
  - SUCCESS
  - SPL
  POINTGOAL_WITH_GPS_COMPASS_SENSOR:
    DIMENSIONALITY: 2
    GOAL_FORMAT: POLAR
  SENSORS:
  - POINTGOAL_WITH_GPS_COMPASS_SENSOR
  SUCCESS:
    SUCCESS_DISTANCE: 0.2
  TYPE: Nav-v0
